from typing import Dict, List,Literal, Any

items=Literal[
        "aketine",
        "aketine-powder",
        "aketine-seed",
        "amber-rice-seed",
        "amethyst-bottle",
        "amethyst-bottle-1",
        "amethyst-bottle-10",
        "amethyst-bottle-11",
        "amethyst-bottle-2",
        "amethyst-bottle-3",
        "amethyst-bottle-4",
        "amethyst-bottle-5",
        "amethyst-bottle-6",
        "amethyst-bottle-7",
        "amethyst-bottle-8",
        "amethyst-bottle-9",
        "amethyst-component",
        "amethyst-fiber",
        "amethyst-part",
        "amethyst-powder",
        "blueprint",
        "buck-capsule-a",
        "buck-capsule-b",
        "buck-capsule-c",
        "buckflower",
        "buckflower-powder",
        "buckflower-seed",
        "bumper-rich",
        "canned-citrome-a",
        "canned-citrome-b",
        "canned-citrome-c",
        "carbon",
        "carbon-powder",
        "citrome",
        "citrome-powder",
        "citrome-seed",
        "clean-water",
        "cryston-bottle",
        "cryston-bottle-1",
        "cryston-bottle-10",
        "cryston-bottle-11",
        "cryston-bottle-2",
        "cryston-bottle-3",
        "cryston-bottle-4",
        "cryston-bottle-5",
        "cryston-bottle-6",
        "cryston-bottle-7",
        "cryston-bottle-8",
        "cryston-bottle-9",
        "cryston-component",
        "cryston-fiber",
        "cryston-part",
        "cryston-powder",
        "cuprium",
        "cuprium-bottle",
        "cuprium-bottle-1",
        "cuprium-bottle-10",
        "cuprium-bottle-11",
        "cuprium-bottle-2",
        "cuprium-bottle-3",
        "cuprium-bottle-4",
        "cuprium-bottle-5",
        "cuprium-bottle-6",
        "cuprium-bottle-7",
        "cuprium-bottle-8",
        "cuprium-bottle-9",
        "cuprium-component",
        "cuprium-part",
        "cuprium-powder",
        "cuprium-solution",
        "dense-carbon-powder",
        "dense-ferrium-powder",
        "dense-originium-powder",
        "dense-origocrust-powder",
        "experimental-heavy-xiranite-bottle",
        "experimental-heavy-xiranite-bottle-1",
        "experimental-heavy-xiranite-part",
        "experimental-xiran-hue-atomizer",
        "experimental-xiranite-bottle",
        "experimental-xiranite-part",
        "ferrium",
        "ferrium-bottle",
        "ferrium-bottle-1",
        "ferrium-bottle-10",
        "ferrium-bottle-11",
        "ferrium-bottle-2",
        "ferrium-bottle-3",
        "ferrium-bottle-4",
        "ferrium-bottle-5",
        "ferrium-bottle-6",
        "ferrium-bottle-7",
        "ferrium-bottle-8",
        "ferrium-bottle-9",
        "ferrium-component",
        "ferrium-part",
        "ferrium-powder",
        "ground-buckflower-powder",
        "ground-citrome-powder",
        "hc-valley-battery",
        "heavy-xiranite",
        "hetonite",
        "hetonite-bottle",
        "hetonite-bottle-1",
        "hetonite-bottle-10",
        "hetonite-bottle-11",
        "hetonite-bottle-2",
        "hetonite-bottle-3",
        "hetonite-bottle-4",
        "hetonite-bottle-5",
        "hetonite-bottle-6",
        "hetonite-bottle-7",
        "hetonite-bottle-8",
        "hetonite-bottle-9",
        "hetonite-component",
        "hetonite-part",
        "hetonite-solution",
        "industrial-explosive",
        "inert-xircon-effluent",
        "jincao",
        "jincao-drink",
        "jincao-powder",
        "jincao-seed",
        "jincao-solution",
        "jincao-tea",
        "lc-valley-battery",
        "lc-wuling-battery",
        "liquid-heavy-xiranite",
        "liquid-xiranite",
        "originium-powder",
        "origocrust",
        "origocrust-powder",
        "packed-origocrust",
        "precipitation-acid",
        "redjade-ginseng-seed",
        "reed-rye-seed",
        "sandleaf",
        "sandleaf-powder",
        "sandleaf-seed",
        "sc-valley-battery",
        "sc-wuling-battery",
        "sewage",
        "stabilized-carbon",
        "steel",
        "steel-bottle",
        "steel-bottle-1",
        "steel-bottle-10",
        "steel-bottle-11",
        "steel-bottle-2",
        "steel-bottle-3",
        "steel-bottle-4",
        "steel-bottle-5",
        "steel-bottle-6",
        "steel-bottle-7",
        "steel-bottle-8",
        "steel-bottle-9",
        "steel-part",
        "tartpepper-seed",
        "xiranite",
        "xiranite-component",
        "xiranite-gourd",
        "xiranite-jade-gourd",
        "xircon",
        "xircon-effluent",
        "yazhen",
        "yazhen-powder",
        "yazhen-seed",
        "yazhen-solution",
        "yazhen-syringe-a",
        "yazhen-syringe-c"
    ]
    
def format_blueprints(
    data: dict ,
    by_views: bool = False,
    by_likes: bool = False,
    region:Literal["Americas/Europe","Asia","Both"]="Both",
    item_filter: Literal["all"] | items = "all",
    _from:int=0,
    _to:int=10
)-> tuple[List[Dict[str, Any]], int]:
    """Format and filter blueprints.

    item_filter may be:
      - "all" (default, no filtering)
      - a string (partial slug)
    """
    if region!="Both":
        data=[d for d in data if d["ingame_region"]==region]
        
    view_key = "view_count"
    like_key = "like_count_cache"
    slug = "slug"
    # para sluge is partial , return all blueprints that start with the string
    if item_filter!="all":
        if isinstance(item_filter, str):
            data = [d for d in data if d[slug].startswith(item_filter)]
        elif isinstance(item_filter, list):
            data = [d for d in data if any(d[slug].startswith(f) for f in item_filter)]

    if by_views:
        data = sorted(data, key=lambda x: x.get(view_key, 0), reverse=True)
    if by_likes:
        data = sorted(data, key=lambda x: x.get(like_key, 0), reverse=True)

    return data[_from:_to] , len(data)